name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Lint
        run: cargo fmt --check
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
